//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// MFCKIOSK.rc에서 사용되고 있습니다.
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MFC_KIOSK_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDB_BITMAP1                     130
#define IDB_BITMAP2                     133
#define IDB_BITMAP3                     134
#define IDB_BITMAP_B1                   135
#define IDB_BITMAP_B2                   136
#define IDB_BITMAP_B3                   137
#define IDB_BITMAP_B4                   138
#define IDB_BITMAP_B5                   139
#define IDB_BITMAP_B6                   140
#define IDB_BITMAP_B7                   141
#define IDB_BITMAP_B8                   142
#define IDB_BITMAP_B9                   143
#define IDB_BITMAP_B10                  144
#define IDB_BITMAP_C1                   145
#define IDB_BITMAP_C2                   146
#define IDB_BITMAP_C3                   147
#define IDB_BITMAP_C4                   148
#define IDB_BITMAP_C5                   149
#define IDB_BITMAP_C6                   150
#define IDB_BITMAP_C7                   151
#define IDB_BITMAP_C8                   152
#define IDB_BITMAP_C9                   153
#define IDB_BITMAP_C10                  154
#define IDB_BITMAP_C11                  155
#define IDB_BITMAP_CR1                  156
#define IDB_BITMAP_CR2                  157
#define IDB_BITMAP_CR3                  158
#define IDB_BITMAP_CR4                  159
#define IDB_BITMAP_CR5                  160
#define IDB_BITMAP_T1                   162
#define IDB_BITMAP_T3                   164
#define IDB_BITMAP_T4                   165
#define IDB_BITMAP_T5                   166
#define IDB_BITMAP_T6                   167
#define IDB_BITMAP_EMPTY                168
#define IDB_BITMAP_T2                   169
#define IDD_DIALOG_MOFAL_PAY            172
#define IDB_BITMAP_KAKAO                178
#define IDB_BITMAP_NAVER                179
#define IDB_BITMAP_PAYCO                180
#define IDB_BITMAP4                     182
#define IDB_BITMAP_CARD                 182
#define IDR_GIF1                        184
#define IDD_DIALOG_LOADING              185
#define IDC_BUTTON_CRAFT                1001
#define IDC_BUTTON_TEA                  1002
#define IDC_BUTTON_BREAD                1003
#define IDC_BUTTON_COFFEE               1004
#define IDC_BUTTON_HERE                 1005
#define IDC_BUTTON_TOGO                 1006
#define IDC_PICTUREBOX1                 1007
#define IDC_PICTUREBOX2                 1008
#define IDC_PICTUREBOX3                 1009
#define IDC_PICTUREBOX4                 1010
#define IDC_PICTUREBOX5                 1011
#define IDC_PICTUREBOX6                 1012
#define IDC_PICTUREBOX7                 1013
#define IDC_PICTUREBOX8                 1014
#define IDC_PICTUREBOX9                 1015
#define IDC_TEXT1                       1016
#define IDC_TEXT2                       1017
#define IDC_TEXT3                       1018
#define IDC_TEXT4                       1019
#define IDC_TEXT5                       1020
#define IDC_TEXT6                       1021
#define IDC_TEXT7                       1022
#define IDC_TEXT8                       1023
#define IDC_TEXT9                       1024
#define IDC_PRICE1                      1025
#define IDC_BUTTON_UP                   1026
#define IDC_BUTTON_DOWN                 1027
#define IDC_TEXT_ORDER1                 1028
#define IDC_TEXT_ORDER14                1028
#define IDC_TEXT_ORDER1_SUM             1029
#define IDC_TEXT_ORDER2_SUM             1030
#define IDC_TEXT_ORDER3_SUM             1031
#define IDC_TEXT_ORDER4_SUM             1032
#define IDC_TEXT_ORDER5_SUM             1033
#define IDC_PRICE2                      1034
#define IDC_PRICE3                      1035
#define IDC_PRICE4                      1036
#define IDC_PRICE5                      1037
#define IDC_PRICE6                      1038
#define IDC_PRICE7                      1039
#define IDC_PRICE8                      1040
#define IDC_PRICE9                      1041
#define IDC_TEXT_ORDER6_SUM             1042
#define IDC_TEXT_ORDER2                 1043
#define IDC_TEXT_ORDER13                1043
#define IDC_TEXT_ORDER3                 1044
#define IDC_TEXT_ORDER14_2              1044
#define IDC_TEXT_ORDER4                 1045
#define IDC_TEXT_ORDER15                1045
#define IDC_TEXT_ORDER5                 1046
#define IDC_TEXT_ORDER16                1046
#define IDC_TEXT_ORDER6                 1047
#define IDC_TEXT_ORDER12                1047
#define IDC_TEXT_ORDER7                 1048
#define IDC_TEXT_ORDER17                1048
#define IDC_TEXT_ORDER8                 1049
#define IDC_TEXT_ORDER18                1049
#define IDC_TEXT_ORDER7_SUM             1050
#define IDC_TEXT_ORDER8_SUM             1051
#define IDC_EDIT1                       1052
#define IDC_EDIT2                       1053
#define IDC_EDIT3                       1054
#define IDC_EDIT4                       1055
#define IDC_EDIT5                       1056
#define IDC_EDIT6                       1057
#define IDC_EDIT7                       1058
#define IDC_EDIT8                       1059
#define IDC_TEXT_ALLSUM                 1060
#define IDC_BUTTON_KOREAN               1061
#define IDC_BUTTON_ENGLISH              1062
#define IDC_BUTTON_CHINESE              1063
#define IDC_TEXT_ORDER19                1064
#define IDC_BUTTON_KAKAO                1065
#define IDC_BUTTON_NAVER                1066
#define IDC_BUTTON_CARD                 1067
#define IDC_BUTTON_PAYCO                1068
#define IDC_BUTTON_BACK                 1069
#define IDC_STATIC_LOADING              1071
#define IDC_letf1                       1074
#define IDC_right1                      1075
#define IDC_CANC1                       1076
#define IDC_letf2                       1081
#define IDC_letf3                       1082
#define IDC_letf4                       1083
#define IDC_letf5                       1085
#define IDC_letf6                       1086
#define IDC_letf7                       1087
#define IDC_letf8                       1088
#define IDC_right2                      1089
#define IDC_right3                      1090
#define IDC_right4                      1091
#define IDC_right5                      1092
#define IDC_right6                      1093
#define IDC_right7                      1094
#define IDC_right8                      1096
#define IDC_CANC2                       1099
#define IDC_CANC3                       1100
#define IDC_CANC4                       1101
#define IDC_CANC5                       1103
#define IDC_CANC6                       1104
#define IDC_CANC7                       1105
#define IDC_CANC8                       1106

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        183
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1077
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
